apiVersion: apps/v1
kind: Deployment
metadata:
  name: recipe-finder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recipe-finder
  template:
    metadata:
      labels:
        app: recipe-finder
    spec:
      containers:
        - name: recipe-finder-container
          image: elankumaran21/recipe-finder:latest
          ports:
            - containerPort: 3000  # Frontend port
            - containerPort: 5000  # Backend port
