apiVersion: v1
kind: Service
metadata:
  name: recipe-finder-service
spec:
  selector:
    app: recipe-finder
  ports:
    - name: frontend-port
      protocol: TCP
      port: 80      # This will be the port exposed externally
      targetPort: 3000  # Frontend's port
    - name: backend-port
      protocol: TCP
      port: 5000    # Backend port for API
      targetPort: 5000
  type: NodePort
